GET http://localhost:3000?id=5 HTTP/1.1

###

POST http://localhost:3000 HTTP/1.1
Content-Type: application/json

{
    "name": "Alvaro",
    "surname": "Barrero",
    "age": 15,
    "adress": {
        "country": "Spain",
        "city": "Madrid"
    }
}