POST  http://localhost:3000/cursos HTTP/1.1
Content-Type: aplication/json

{
    "id": 55,
    "title": "hola"
}

###

PUT  http://localhost:3000/cursos HTTP/1.1
Content-Type: aplication/json

{
    "id": 55,
    "title": "hola"
}